version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: cryptomusPet
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Denys7227221
      - POSTGRES_DB=cryptomusDB
    command: postgres
    restart: always
