version: '3.8'
services:
  postgres:
    image: postgres
    container_name: AuthPrisma
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Denys7227221
      - POSTGRES_DB=AuthPrisma
    command: postgres
    restart: always
