version: '3.8'
services:
  postgres:
    image: postgres
    container_name: AuthPrisma
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: postgres
    restart: always